# .github/workflows/account_creator.yml

name: Continuous Account Creation (Parallel)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  create-accounts:
    strategy:
      fail-fast: false
      matrix:
        # SOLUTION A: Reduced the number of parallel jobs from 15 to 5.
        # You can experiment by increasing this number later if needed.
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

    runs-on: ubuntu-latest
    name: 'Create Account (Job ${{ matrix.job_id }})'
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # SOLUTION B: Add a random delay to stagger the start of each job.
      - name: Stagger job start
        run: sleep $((RANDOM % 60))s

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dist/proxy_scraper_checker-0.1.0-cp312-cp312-manylinux_2_34_x86_64.whl

      - name: Run Account Creation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python AccountCreation.py
