# .github/workflows/account_creator.yml

name: Continuous Account Creation (Parallel)

on:
  schedule:
    # This runs the workflow every 5 minutes.
    - cron: '*/5 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab for testing.
  workflow_dispatch:

jobs:
  create-accounts:
    strategy:
      fail-fast: false
      matrix:
        # This list creates 15 parallel jobs. The compact syntax is easier to read.
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

    runs-on: ubuntu-latest
    name: 'Create Account (Job ${{ matrix.job_id }})'
    
    # Reduced timeout to a more reasonable value for a frequently scheduled job.
    timeout-minutes: 30 
    
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # CORRECTED: Changed `run: >` to `run: |` to preserve newlines
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dist/proxy_scraper_checker-0.1.0-cp312-cp312-manylinux_2_34_x86_64.whl

      - name: Run Account Creation Script
        env:
          # This is the standard, clean way to reference the token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python AccountCreation.py
